name: hive_local_storage
description: A cache helper which wraps hive_ce to make it easy to store and encrypt local data
version: 3.0.0
homepage: https://github.com/kishormainali/hive_local_storage
repository: https://github.com/kishormainali/hive_local_storage
topics:
  - local-storage
  - cache
  - hive
  - encryption

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.20.1
  hive_ce_flutter: ^2.4.0
  flutter_secure_storage: ^11.2.0

  collection: any
  synchronized: ^3.4.2

  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=6.0.0 <7.0.0"
